# Generated by Django 4.2.1 on 2023-05-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_catogory_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catogory',
            name='img',
            field=models.ImageField(default=None, upload_to='Catogory'),
        ),
    ]
